return {
	AUTOCMD_GROUP_NAME_PREFIX = "STTUSLINE_",
	HIGHLIGHT_COMPONENT_PREFIX = "STTUSLINE_COMP_HIGHLIGHT_",
	COMPONENT_MODULE_PREFIX = "sttusline.components",
	DIAGNOSTICS_HIGHLIGHT_PREFIX = "STTUSLINE_DIAGNOSTICS_",
}
